# Generated by Django 4.0 on 2022-01-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("auth", "0012_alter_user_first_name_max_length")]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_id",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.user"
                    ),
                ),
            ],
            options={"db_table": "booking"},
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
            ],
            options={"db_table": "city"},
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="media")),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ENGLISH", "English"),
                            ("HINDI", "Hindi"),
                            ("KANNADA", "Kannada"),
                            ("TAMIL", "Tamil"),
                            ("TELUGU", "Telugu"),
                            ("MALAYALAM", "Malayalam"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"db_table": "movie"},
        ),
        migrations.CreateModel(
            name="Theatre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
                ("total_screens", models.IntegerField(default=1)),
                (
                    "fk_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.city"
                    ),
                ),
            ],
            options={"db_table": "theatre"},
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screen", models.IntegerField(default=1)),
                ("timing", models.DateTimeField()),
                ("duration", models.IntegerField(default=150)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.movie",
                    ),
                ),
                (
                    "theatre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.theatre",
                    ),
                ),
            ],
            options={"db_table": "show"},
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=3, null=True)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.show"
                    ),
                ),
            ],
            options={"db_table": "seat", "unique_together": {("number", "show")}},
        ),
        migrations.CreateModel(
            name="SeatBooked",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.booking",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.seat"
                    ),
                ),
            ],
            options={
                "db_table": "bookedSeats",
                "unique_together": {("seat", "booking")},
            },
        ),
    ]
